# Generated by Django 4.1.4 on 2023-04-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvmodel',
            name='uploaded_at',
        ),
    ]
